Make implementation of Sprint 14
StanislavFishkov/java-shareit pull request #1
Opened 2024-09-14 22:05 UTC by StanislavFishkov

2024-09-16 05:12 UTC, z8q requested changes

2024-09-16 05:12 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        return existingItem.get();
можно попробовать немного оптимизировать

```JAVA
return getById(itemId)
        .orElseThrow(() -> new NotFoundException("item doesn't exist with id: " + itemId));
```

2024-09-16 17:54 UTC, StanislavFishkov commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        return existingItem.get();
Да, так красивее! Спасибо, исправил.

2024-09-17 14:02 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody NewItemDto newItemDto) {
Интересно, что может повлиять,
я еще попробовал исправить на примитив вот этот метод
```JAVA
    @GetMapping("/{itemId}")
    public ItemDto get(@RequestHeader("X-Sharer-User-Id") long userId, @PathVariable Long itemId) {
        return itemService.get(userId, itemId);
    }
```
через insomnia сделал запрос
```
curl --request GET \
  --url http://localhost:8080/items/1 \
  --header 'X-Sharer-User-Id: '
```
отработало, как писал)

2024-09-17 14:02 UTC, z8q approved these changes

2024-09-17 14:12 UTC, merged