Make implementation of Sprint 15
StanislavFishkov/java-shareit pull request #2
Opened 2024-09-23 00:20 UTC by StanislavFishkov

2024-09-23 19:37 UTC, z8q requested changes

2024-09-23 19:37 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("Select b from Booking as b where booker.id = ?1 and ?2 between start and end order by start desc")
Если в методе перед аргументами поставить аннотацию Param такого вида
```
@Param("bookerId") Long bookerId
```
то в запросе можно будет указать без цифр
```
@Query("Select b from Booking as b where booker.id = :bookerId and ?2 between ...")
```

2024-09-23 19:37 UTC, z8q commented on src/main/resources/schema.sql
> +  email VARCHAR(512) NOT NULL,
для email большой ограничитель

2024-09-23 19:37 UTC, z8q commented on src/main/resources/schema.sql
> +  description VARCHAR NOT NULL,
на description можно определить ограничитель

2024-09-23 19:37 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .map(item -> itemMapper.toDto(item, commentRepository.findByItemIdOrderByCreatedDesc(item.getId()),
Стоит сокращать по возможности количество обращений к базам (если можно одним запросом передать сразу список аргументов,  лучше это делать)
В дипломе особенно внимательно будут проверять обращения в циклах и стримах)
Обычно не очень хорошо сказывается на производительности

2024-09-24 12:52 UTC, StanislavFishkov commented on src/main/resources/schema.sql
> +  description VARCHAR NOT NULL,
Установил ограничитель.

2024-09-24 13:02 UTC, StanislavFishkov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("Select b from Booking as b where booker.id = ?1 and ?2 between start and end order by start desc")
Исправил, действительно так запрос "читабельней", спасибо.

2024-09-25 01:28 UTC, StanislavFishkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .map(item -> itemMapper.toDto(item, commentRepository.findByItemIdOrderByCreatedDesc(item.getId()),
Готово, исправил.

2024-09-25 18:14 UTC, z8q approved these changes

2024-09-26 16:59 UTC, merged